// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDocker() {
  return window['go']['main']['App']['CheckDocker']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function InstallProject() {
  return window['go']['main']['App']['InstallProject']();
}
