// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDocker():Promise<main.CheckResult>;

export function CloseApp():Promise<void>;

export function InstallProject():Promise<main.CheckResult>;
