x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    logging: *default-logging
    expose:
      - 8008
    volumes:
      - ./matrix/data:/data
    depends_on:
      synapse_db:
        condition: service_healthy
    environment:
      - SYNAPSE_REPORT_STATS=no
    deploy:
      resources:
        limits:
          memory: 1.5G

  synapse_db:
    container_name: synapse_db
    logging: *default-logging
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB_SYNAPSE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    logging: *default-logging
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
    volumes:
      - ./nginx/templates/local.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/www:/usr/share/nginx/html:ro
      - ./certs:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - synapse
      - navidrome
      - audiobookshelf
      - nextcloud
      - vaultwarden
      - portainer
    deploy:
      resources:
        limits:
          memory: 512M

  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    container_name: certbot
    logging: *default-logging
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/var/lib/letsencrypt
      - ./certbot-dns-webnames:/opt/certbot-dns-webnames
    environment:
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
    command: >
      certonly
      --manual
      --manual-auth-hook /opt/certbot-dns-webnames/authenticator.sh
      --manual-cleanup-hook /opt/certbot-dns-webnames/cleanup.sh
      --preferred-challenges dns-01
      --agree-tos
      --no-eff-email
      --non-interactive
      -d "${SYNAPSE_SERVER_NAME}"
      -d "*.${SYNAPSE_SERVER_NAME}"
      --email "${EMAIL}"
    deploy:
      resources:
        limits:
          memory: 512M

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "9113:9113"
    command: --nginx.scrape-uri=http://nginx_proxy:8080/stub_status
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          memory: 512M

  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    logging: *default-logging
    expose:
      - 4533
    environment:
      ND_SCANINTERVAL: "1m"
      ND_LOGLEVEL: "info"
      ND_BASEURL: "/navidrome"
    volumes:
      - ./navidrome/data:/data
      - /home/${HOME_USER_NAME}/Music:/music:ro
    deploy:
      resources:
        limits:
          memory: 512M

  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf:latest
    logging: *default-logging
    restart: unless-stopped
    expose:
      - 80
    environment:
      - AUDIOBOOKSHELF_PORT=80
      - AUDIOBOOKSHELF_BASE_PATH=/audiobookshelf
    volumes:
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
      - /home/${HOME_USER_NAME}/Audiobooks:/audiobooks
      - /home/${HOME_USER_NAME}/Podcasts:/podcasts
      - /home/${HOME_USER_NAME}/Books:/books
    deploy:
      resources:
        limits:
          memory: 512M

  nextcloud_db:
    image: postgres:18
    container_name: nextcloud_db
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - nextcloud_db_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NEXTCLOUD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    logging: *default-logging
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      nextcloud_db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_DB=${POSTGRES_DB_NEXTCLOUD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OVERWRITEWEBROOT=/nextcloud
      - OVERWRITEPROTOCOL=https
      - HTACCESS_OVERRIDE_CURRENT=1
    volumes:
      - ./nextcloud/html:/var/www/html
      - /home/${HOME_USER_NAME}/NextcloudData:/var/www/html/data
    deploy:
      resources:
        limits:
          memory: 1.5G

  nextcloud_configure:
    image: nextcloud:stable
    container_name: nextcloud_configure
    logging: *default-logging
    restart: "no"
    user: www-data
    depends_on:
      - nextcloud
    volumes:
      - ./nextcloud/html:/var/www/html
      - /home/${HOME_USER_NAME}/NextcloudData:/var/www/html/data
    entrypoint: /bin/sh
    command: >
      -c "
      echo 'Waiting for Nextcloud to be installed...';
      until [ -f /var/www/html/config/config.php ]; do sleep 2; done;
      sleep 15;
        
      echo 'Applying system fixes...';

      php occ config:system:set trusted_domains 1 --value='${SYNAPSE_SERVER_NAME}';
      php occ config:system:set trusted_proxies 0 --value='172.16.0.0/12';

      php occ config:system:set maintenance_window_start --value=2 --type=int;
      php occ background-job:set cron;

      php occ config:system:set default_phone_region --value='RU';
      php occ config:system:set filelocking.enabled --value=true --type=boolean;
      php occ config:system:set memcache.local --value='\\OC\\Memcache\\APCu';
        
      echo 'Applying migrations and htaccess...';
      php occ maintenance:repair --include-expensive --no-interaction;
      php occ maintenance:update:htaccess;
        
      echo 'Configuration applied successfully!';
      "
    deploy:
      resources:
        limits:
          memory: 512M

  vaultwarden_db:
    image: postgres:18
    container_name: vaultwarden_db
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - vaultwarden_db_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB_VAULTWARDEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    logging: *default-logging
    restart: unless-stopped
    expose:
      - 80
      - 3012
    depends_on:
      vaultwarden_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@vaultwarden_db:5432/${POSTGRES_DB_VAULTWARDEN}
      - DOMAIN=https://${SYNAPSE_SERVER_NAME}/vaultwarden
      - SIGNUPS_ALLOWED=true
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_HASH}
    volumes:
      - ./vaultwarden/data:/data
    deploy:
      resources:
        limits:
          memory: 512M

  prometheus_init:
    image: alpine:latest
    container_name: prometheus_init
    restart: "no"
    logging: *default-logging
    user: "root"
    volumes:
      - ./prometheus:/mnt/prometheus
      - ./grafana:/mnt/grafana
    command: >
      sh -c "
      mkdir -p /mnt/prometheus/data && 
      chown -R 65534:65534 /mnt/prometheus/data &&
      mkdir -p /mnt/grafana/data &&
      chown -R 472:472 /mnt/grafana/data
      "
    deploy:
      resources:
        limits:
          memory: 512M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    logging: *default-logging
    restart: unless-stopped
    expose:
      - 9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - ./monitoring/targets.json:/etc/prometheus/targets.json:ro
      - ./prometheus/data:/prometheus
    depends_on:
      prometheus_init:
        condition: service_completed_successfully
      node_exporter:
        condition: service_started
      cadvisor:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    logging: *default-logging
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - GF_SERVER_ROOT_URL=https://${SYNAPSE_SERVER_NAME}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      prometheus_init:
        condition: service_completed_successfully
      prometheus:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    logging: *default-logging
    restart: unless-stopped
    network_mode: "host"
    pid: "host"
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /run/udev:/run/udev:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/rootfs/(sys|proc|dev|host|etc|var/lib/docker)($$|/)"
    deploy:
      resources:
        limits:
          memory: 512M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.54.1
    container_name: cadvisor
    logging: *default-logging
    restart: unless-stopped
    privileged: true
    ports:
      - "8090:8090"
    command:
      - "--allow_dynamic_housekeeping=true"
      - "--housekeeping_interval=10s"
      - "--disable_metrics=disk,referenced_memory"
      - "--raw_cgroup_prefix_whitelist=/system.slice,/user.slice"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev:/dev:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/fs/cgroup:/cgroup:ro
    deploy:
      resources:
        limits:
          memory: 512M

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    logging: *default-logging
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    deploy:
      resources:
        limits:
          memory: 512M

  monitoring_configure:
    image: alpine:3.20
    container_name: monitoring_configure
    logging: *default-logging
    volumes:
      - ./monitoring:/mnt/monitoring
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MATRIX_BOT_USERNAME=${MATRIX_BOT_USERNAME}
      - MATRIX_BOT_PASSWORD=${MATRIX_BOT_PASSWORD}
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
      - ADMIN_USER=${ADMIN_USER}
      - MONITORING_SECRET=${MONITORING_SECRET}
    command: >
      sh -c "
        apk add --no-cache curl jq gettext docker-cli;

        echo 'Ожидание запуска Synapse API...';
        until curl -s http://synapse:8008/_matrix/client/versions; do sleep 3; done;

        echo '1. Регистрация пользователя бота в Matrix...';
        docker exec synapse register_new_matrix_user -c /data/homeserver.yaml -u \"$MATRIX_BOT_USERNAME\" -p \"$MATRIX_BOT_PASSWORD\" --no-admin || echo 'Пользователь уже существует, пропускаем';

        echo '2. Получение Access Token для бота...';
        BOT_TOKEN=$$(curl -s -X POST -H 'Content-Type: application/json' -d \"{\\\"type\\\":\\\"m.login.password\\\",\\\"identifier\\\":{\\\"type\\\":\\\"m.id.user\\\",\\\"user\\\":\\\"$MATRIX_BOT_USERNAME\\\"},\\\"password\\\":\\\"$MATRIX_BOT_PASSWORD\\\"}\" http://synapse:8008/_matrix/client/v3/login | jq -r '.access_token');

        if [ \"$$BOT_TOKEN\" = \"null\" ] || [ -z \"$$BOT_TOKEN\" ]; then
          echo 'ОШИБКА: Не удалось получить токен бота!'; exit 1;
        fi;

        echo '3. Создание комнаты и получение её внутреннего ID (!)...';
        CREATE_ROOM_RESP=$$(curl -s -X POST -H \"Authorization: Bearer $$BOT_TOKEN\" -H 'Content-Type: application/json' -d \"{\\\"visibility\\\":\\\"private\\\",\\\"room_alias_name\\\":\\\"server-alerts\\\",\\\"name\\\":\\\"Server Alerts\\\",\\\"preset\\\":\\\"private_chat\\\",\\\"invite\\\":[\\\"@$ADMIN_USER:$SYNAPSE_SERVER_NAME\\\"]}\" http://synapse:8008/_matrix/client/v3/createRoom);
        
        ERRCODE=$$(echo \"$$CREATE_ROOM_RESP\" | jq -r '.errcode');
        
        if [ \"$$ERRCODE\" = \"M_ROOM_IN_USE\" ]; then
          echo '-> Комната уже существует, получаем её ID...';
          ROOM_ID=$$(curl -s http://synapse:8008/_matrix/client/v3/directory/room/%23server-alerts%3A${SYNAPSE_SERVER_NAME} | jq -r '.room_id');
        else
          ROOM_ID=$$(echo \"$$CREATE_ROOM_RESP\" | jq -r '.room_id');
          echo '-> Комната успешно создана, инвайт отправлен!';
        fi;

        echo '4. Передача динамических данных для matrix_alertmanager...';
        echo \"export MATRIX_TOKEN=$$BOT_TOKEN\" > /mnt/monitoring/bot_env.sh;
        echo \"export MATRIX_INTERNAL_ROOM_ID=$$ROOM_ID\" >> /mnt/monitoring/bot_env.sh;

        echo '5. Генерация alertmanager.yml на основе шаблона...';
        envsubst < /mnt/monitoring/alertmanager.template.yml > /mnt/monitoring/alertmanager.yml;

        echo 'Мониторинг успешно сконфигурирован!';
      "
    depends_on:
      synapse:
        condition: service_started
      prometheus_init:
        condition: service_completed_successfully

  matrix_alertmanager:
    image: jaywink/matrix-alertmanager:latest
    container_name: matrix_alertmanager
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - ./monitoring:/mnt/monitoring:ro
    environment:
      - MATRIX_HOMESERVER_URL=http://synapse:8008
      - MATRIX_USER=@${MATRIX_BOT_USERNAME}:${SYNAPSE_SERVER_NAME}
      - APP_ALERTMANAGER_SECRET=${MONITORING_SECRET}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Ожидание файла окружения от конфигуратора...";
        until [ -f /mnt/monitoring/bot_env.sh ]; do sleep 1; done;

        echo "Чтение токена и ID комнаты...";
        . /mnt/monitoring/bot_env.sh

        echo "Настройка маршрутизации (Ресивер -> Внутренний ID)..."
        export MATRIX_ROOMS="matrix-room-alerts/$${MATRIX_INTERNAL_ROOM_ID}"

        echo "Запуск matrix-alertmanager...";
        exec node src/app.js
    depends_on:
      synapse:
        condition: service_started
      monitoring_configure:
        condition: service_completed_successfully

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    expose:
      - 9093
    depends_on:
      prometheus:
        condition: service_started
      monitoring_configure:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 512M
  
  amnezia-client:
    image: amnezia-awg2
    container_name: amnezia-client
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules:ro
       ./amnezia-data/client_home.conf:/opt/amnezia/awg/awg0.conf:rw
    logging: *default-logging

  heartbeat_to_vps:
    image: alpine:latest
    container_name: heartbeat_to_vps
    user: root
    restart: always
    environment:
      - SERVER_IP=10.8.1.1
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASSWORD}
    command: |
      sh -c '
      apk add --no-cache curl jq

      echo "Авторизация..."
      TOKEN=$$(curl -s -X POST "http://$$SERVER_IP:3001/api/v1/login" \
        -H "Content-Type: application/json" \
        -d "$$(printf "{\x22username\x22:\x22%s\x22,\x22password\x22:\x22%s\x22}" "$$ADMIN_USER" "$$ADMIN_PASS")" | jq -r ".token")

      if [ -z "$$TOKEN" ] || [ "$$TOKEN" = "null" ]; then
        echo "ОШИБКА: Не удалось получить токен авторизации!"
        exit 1
      fi

      echo "Получение Push-токена..."
      PUSH_TOKEN=$$(curl -s -X GET "http://$$SERVER_IP:3001/api/v1/monitor" -H "Authorization: Bearer $$TOKEN" | jq -r ".[] | select(.name==\x22Home-Server\x22) | .pushToken")
        
      if [ -z "$$PUSH_TOKEN" ] || [ "$$PUSH_TOKEN" = "null" ]; then
        echo "ОШИБКА: Не удалось получить Push-токен! Убедитесь, что в Kuma создан хотя бы один монитор."
        exit 1
      fi

      echo "Запуск бесконечного цикла пингов (токен: $$PUSH_TOKEN)..."
      while true; do
        curl -sS "http://$$SERVER_IP:3001/api/push/$$PUSH_TOKEN?status=up&msg=OK" > /dev/null
        sleep 60
      done
      '

volumes:
  synapse_db_data:
  nextcloud_db_data:
  vaultwarden_db_data:
