FROM amneziavpn/amnezia-wg:latest

RUN apt-get update && apt-get install -y bash

COPY amnezia-tools/awg-quick /usr/local/bin/awg-quick
RUN chmod +x /usr/local/bin/awg-quick

COPY amnezia-tools/awg /usr/local/bin/awg 
RUN chmod +x /usr/local/bin/awg

CMD ["bash", "-c", "awg-quick up /opt/amnezia/awg/awg0.conf"]