x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  nginx:
    image: nginx:stable
    container_name: nginx_vps
    logging: *default-logging
    restart: unless-stopped
    network_mode: "host"
    environment:
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./configs/nginx/templates/nginx.remote.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./configs/nginx/www:/usr/share/nginx/html:ro
      - ./certbot/certs:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      wg-easy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/vps-health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    container_name: certbot
    logging: *default-logging
    volumes:
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/certs-data:/var/lib/letsencrypt
      - ./certbot/certbot-dns-webnames:/opt/certbot-dns-webnames
    environment:
      - SERVER_NAME=${SERVER_NAME}
    command: >
      certonly
      --manual
      --manual-auth-hook /opt/certbot-dns-webnames/authenticator.sh
      --manual-cleanup-hook /opt/certbot-dns-webnames/cleanup.sh
      --preferred-challenges dns-01
      --agree-tos
      --no-eff-email
      --non-interactive
      --force-renewal
      -d "${SERVER_NAME}"
      -d "*.${SERVER_NAME}"
      --email "${EMAIL}"
    deploy:
      resources:
        limits:
          memory: 1G

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.3
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=${VPS_PUBLIC_IP}
      - PORT=51821
      - WG_PORT=51820
      - WEBROOT_BIND_ADDRESS=127.0.0.1
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=10.8.0.1
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_ALLOWED_IPS=0.0.0.0/0
      - EXPERIMENTAL_AWG=true
      - OVERRIDE_AUTO_AWG=awg
      - INSECURE=true
      - WG_DEVICE=eth0
      - INIT_ENABLED=true
      - INIT_USERNAME=${ADMIN_USER}
      - INIT_PASSWORD=${ADMIN_PASSWORD}
      - INIT_HOST=${VPS_PUBLIC_IP}
      - INIT_PORT=51820
    volumes:
      - ./apps-data/wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    network_mode: "host"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    healthcheck:
      test: ["CMD", "awg", "show", "wg0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  gatus:
    image: twinproduction/gatus:stable
    container_name: gatus
    logging: *default-logging
    restart: unless-stopped
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./configs/gatus:/config
    environment:
      - TZ=Europe/Moscow
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SERVER_NAME=${SERVER_NAME}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      nginx:
        condition: service_healthy

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    restart: unless-stopped
    logging: *default-logging
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: --nginx.scrape-uri=http://host.docker.internal:8080/stub_status
    ports:
      - "10.8.0.1:9113:9113"
    depends_on:
      nginx:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    logging: *default-logging
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./apps-data/adguard/work:/opt/adguardhome/work
      - ./configs/adguard/conf:/opt/adguardhome/conf
    deploy:
      resources:
        limits:
          memory: 512M
  
  adguard-exporter:
    image: ghcr.io/henrywhitaker3/adguard-exporter:latest
    container_name: adguard-exporter
    restart: unless-stopped
    network_mode: "host"
    environment:
      - ADGUARD_SERVERS=http://127.0.0.1:8082
      - ADGUARD_USERNAMES=${ADMIN_USER}
      - ADGUARD_PASSWORDS=${ADMIN_PASSWORD}
      - INTERVAL=15s