FROM alpine:3.22.1

RUN apk --no-cache add \
    iproute2 \
    iptables \
    bash \
    openresolv \
    dumb-init \
    && apk --no-cache add --virtual .build-deps \
    git \
    build-base \
    linux-headers

RUN git clone https://github.com/amnezia-vpn/amneziawg-tools.git /tmp/amneziawg-tools --depth=1 \
    && make -C /tmp/amneziawg-tools/src \
    && make -C /tmp/amneziawg-tools/src install \
    && rm -rf /tmp/amneziawg-tools \
    && apk del .build-deps

COPY scripts/amnezia-client_init.sh /init.sh
RUN chmod +x /init.sh

ENTRYPOINT ["/usr/bin/dumb-init", "/init.sh"]