FROM amneziavpn/amnezia-wg:latest

RUN apk update && apk add --no-cache bash

COPY amnezia-tools/awg-quick /usr/local/bin/awg-quick
COPY amnezia-tools/awg /usr/local/bin/awg

RUN chmod +x /usr/local/bin/awg*

ENV PATH="/usr/local/bin:${PATH}"

CMD ["bash", "-c", "awg-quick up /opt/amnezia/awg/awg0.conf && tail -f /dev/null"]