services:
  ansible:
    image: alpine/ansible:2.21.0
    container_name: ansible
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_CONFIG=/ansible/ansible.cfg
    volumes:
      - .:/ansible:ro
      - ssh-data:/root/.ssh:rw
    entrypoint: ["/bin/sh", "/ansible/scripts/ansible-entrypoint.sh"]
    working_dir: /ansible

volumes:
  ssh-data: