services:
  frps:
    image: snowdreamtech/frps:latest
    container_name: frps
    restart: always
    network_mode: host
    environment:
      - FRP_TOKEN=${FRP_TOKEN}
    volumes:
      - ./frp/frps.toml:/etc/frp/frps.toml:ro