groups:
  - name: container_alerts
    rules:
      - alert: ContainerDown
        expr: (time() - container_last_seen{name!=""}) > 60
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Контейнер {{ $labels.name }} упал!"
          description: "Контейнер {{ $labels.name }} не подает признаков жизни более 1 минуты."

  - name: host_alerts
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Высокая нагрузка на CPU"
          description: "Нагрузка на CPU сервера превышает 90% (текущее значение: {{ $value | printf \"%.2f\" }}%)."

      - alert: LowMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Мало оперативной памяти"
          description: "Доступно менее 10% оперативной памяти (текущее значение: {{ $value | printf \"%.2f\" }}%)."

  - name: disk_alerts
    rules:
      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Заканчивается место на диске"
          description: "Диск заполнен более чем на 85% (текущее значение: {{ $value | printf \"%.2f\" }}%)."
  
  - name: borg_alerts
    rules:
      - alert: BorgBackupStale
        expr: (time() - borg_repository_last_backup_timestamp) > 172800
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Бэкап не обновлялся более 48 часов"
          description: "Последний успешный бэкап в репозитории {{ $labels.repository }} был слишком давно."
      
      - alert: BorgBackupFailed
        expr: borg_backup_last_job_success == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Ошибка бэкапа Borg"
          description: "Последнее задание бэкапа для репозитория {{ $labels.repository }} завершилось неудачей."