# Значения ставить те же, что и в .env (некоторые значения новые, но там и так понятно что ставить)
vps_public_ip: "your_vps_public_ip"
local_private_ip: "your_local_private_ip"
vps_user: "your_vps_username"
local_user: "your_local_username"

synapse_server_name: "your_domain.ru"
admin_user: "admin"
admin_password: "change_this_to_a_very_strong_password"

home_user_name: "serveruser"
email: "your_primary_email@gmail.com"

smtp_host: "smtp.gmail.com"
smtp_port: "465"
smtp_user: "your_alerts_sender@gmail.com"
smtp_password: "your_16_digit_app_password"
smtp_from: "your_alerts_sender@gmail.com"
smtp_to: "your_personal_mailbox@mail.ru"

server_ip: "your_vps_public_ip"

matrix_bot_username: "monitoring-bot"
matrix_bot_password: "strong_bot_password"
monitoring_secret: "generate_random_hex_string"

webnames_apikey: "your_webnames_api_key_here"

postgres_db_nextcloud: "nextcloud"
postgres_db_synapse: "synapse"
postgres_db_vaultwarden: "vaultwarden"
postgres_user: "postgres_master"
postgres_password: "postgres_master_secure_password"

synapse_registration_shared_secret: "generate_random_hex_string_1"
synapse_macaroon_secret_key: "generate_random_hex_string_2"
synapse_form_secret: "generate_random_hex_string_3"

secret_vaultwarden_password: "vaultwarden_admin_panel_secure_password"

ssh_public_key: "ssh_desktop_public_key_where_ansible_is_installed"
