- ✨ Сервисы:
    - Vaultwarden:
        icon: si-bitwarden
        href: /vaultwarden/
        description: Менеджер паролей с 2FA
    - Navidrome:
        icon: mdi-music-circle
        href: /navidrome
        description: Личная медиатека
    - Nextcloud:
        icon: si-nextcloud
        href: /nextcloud
        description: Облако и совместная работа
    - Audiobookshelf:
        icon: si-audiobookshelf
        href: /audiobookshelf
        description: Сервер для аудиокниг
    - AdGuard Home:
        icon: si-adguard
        href: /adguard-home
        description: DNS и блокировка рекламы

- 🛠️ Другие инструменты:
    - Borg UI:
        icon: mdi-backup-restore
        href: /borg-ui
        description: Управление бэкапами
    - Portainer:
        icon: si-portainer
        href: /portainer/
        description: Управление контейнерами
    - Grafana:
        icon: si-grafana
        href: /grafana
        description: Системные метрики
    - WireGuard:
        icon: si-wireguard
        href: /wg-easy/
        description: Управление VPN
    - Gatus:
        icon: mdi-check-network
        href: /gatus/
        description: Аптайм и статус сервисов