title: Домашний Сервер
headerStyle: clean
theme: dark
color: slate
fullWidth: true
useEqualHeights: true
favicon: /app/config/images/favicon.ico
background:
  image: /app/config/images/wallpaper.jpg
  blur: xl
  brightness: 50
  opacity: 50
cardBlur: md
iconStyle: theme
showStats: true
statusStyle: dot