user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

stream {
    server {
        listen 443;
        allow 127.0.0.1;
        allow 10.8.1.0/24;
        deny all;
        proxy_pass 10.8.1.2:443;
        proxy_protocol on;
    }

    server {
        listen 2222;
        proxy_pass 10.8.1.2:22;
    }
}

http {
    server {
        listen 80;
        server_name _;
        allow 127.0.0.1;
        allow 10.8.1.0/24;
        deny all;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 3001;
        server_name _;
        
        location / {
            proxy_pass http://uptime-kuma:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }

    server {
        listen 3002;
        server_name _;
        
        location / {
            proxy_pass http://wg-easy:51821;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}