web:
  address: "127.0.0.1"
  port: 51822

alerting:
  telegram:
    token: "${TELEGRAM_TOKEN}"
    id: "${TELEGRAM_CHAT_ID}"

endpoints:
  - name: "Is Local Server Alive?"
    url: "http://host.docker.internal:8080/health-check"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
        failure-threshold: 3
        success-threshold: 2
        send-on-resolved: true
        description: "Локальный домашний сервер недоступен!"

  - name: "Is VPS Server Alive?"
    url: "http://host.docker.internal:8080/vps-health-check"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
        failure-threshold: 3
        success-threshold: 2
        send-on-resolved: true
        description: "Веб-окружение VPS не отвечает!"

  - name: SSL Certificate
    url: "https://${SERVER_NAME}"
    interval: 1h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 720h"
    alerts:
      - type: telegram
        description: "SSL сертификат скоро истекает"
        failure-threshold: 3
        success-threshold: 2
        send-on-resolved: true
