- name: "Bootstrap: Первичная подготовка операционных систем"
  hosts: vps, local
  gather_facts: no
  vars_files:
    - vars/secrets.yml
  vars:
    ansible_user: root
    ansible_remote_tmp: /tmp/.ansible
  tags: bootstrap
  tasks:
    - name: "Python: Проверка и установка Python3 (необходим для работы Ansible)"
      raw: |
        if command -v apt-get >/dev/null; then
            apt-get update && apt-get install -y python3
        elif command -v pacman >/dev/null; then
            pacman -Sy --noconfirm python3
        else
            echo "Unsupported distribution" >&2
            exit 1
        fi
      changed_when: false
    - name: "Facts: Сбор системных фактов после проверки Python"
      setup:

    - name: "Bootstrap: Запуск сценария базовой настройки"
      include_tasks: tasks/bootstrap_os.yml
  handlers:
    - name: Restart SSH
      systemd:
        name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
        state: restarted

- name: "Настройка удаленной инфраструктуры: setup_remote.sh"
  hosts: vps
  vars_files:
    - vars/secrets.yml
  become: yes
  tasks:
    - name: "VPS | Проверка наличия папки репозитория"
      ansible.builtin.stat:
        path: "/home/{{ vps_user }}/ServeHub-2"
      register: vps_repo_dir
    
    - name: "VPS | Клонирование репозитория, если он отсутствует"
      ansible.builtin.git:
        repo: 'https://github.com/canntstand/ServeHub-2'
        dest: "/home/{{ vps_user }}/ServeHub-2"
        clone: yes
        update: yes
      become_user: "{{ vps_user }}"
      when: not vps_repo_dir.stat.exists

    - name: "Запуск скрипта настройки удаленного сервера"
      shell: "chmod +x scripts/setup_remote.sh && ./scripts/setup_remote.sh"
      args:
        chdir: "/home/{{ vps_user }}/ServeHub-2"

- name: "Ожидание конфигурации WireGuard"
  hosts: localhost
  connection: local
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: "Пауза для генерации конфига"
      ansible.builtin.pause:
        prompt: |
          ======================================================================
          ⚙️ НАСТРОЙКА WIREGUARD И PROMETHEUS (РУЧНОЙ ШАГ):
          ======================================================================
          1. Откройте туннель: ssh -L 51821:127.0.0.1:51821 {{ vps_user }}@{{ hostvars['vps_server']['ansible_host'] }}
          2. Зайдите в браузер: http://127.0.0.1:51821
          3. Включите Prometheus в настройках wg-easy.
          4. Создайте клиента для локального сервера с ip 10.8.0.2 и скачайте файл конфигурации (либо просто скопируйте текст).
          5. Можно также сразу создать клиенты для остальных устройств (можно будет сделать потом)
          6. Сохраните его на вашем локальном сервере по пути: ./configs/amnezia/awg0.conf
          ======================================================================
          Как только файл на месте, нажмите ENTER для продолжения деплоя...

- name: "Настройка локальной инфраструктуры: setup_local.sh"
  hosts: local
  vars_files:
    - vars/secrets.yml
  become: yes
  tasks:
    - name: "Local | Проверка наличия папки репозитория"
      ansible.builtin.stat:
        path: "/home/{{ local_user }}/ServeHub-2"
      register: local_repo_dir

    - name: "Local | Клонирование репозитория, если он отсутствует"
      ansible.builtin.git:
        repo: 'https://github.com/canntstand/ServeHub-2'
        dest: "/home/{{ local_user }}/ServeHub-2"
        clone: yes
        update: yes
      become_user: "{{ local_user }}"
      when: not local_repo_dir.stat.exists

    - name: "Запуск скрипта настройки локального сервера"
      shell: "chmod +x scripts/setup_local.sh && ./scripts/setup_local.sh"
      args:
        chdir: "/home/{{ local_user }}/ServeHub-2"