- name: "[Bootstrap] Проверка: доступен ли root?"
  hosts: vps, local
  gather_facts: no
  vars_files:
    - vars/secrets.yml
  tags: bootstrap

  vars:
    ansible_password: "{{ user_pass }}"
    ansible_ssh_pass: "{{ user_pass }}"

  pre_tasks:
    - name: "[SSH] Проверка: доступен ли root?"
      ansible.builtin.ping:
      ignore_errors: yes
      ignore_unreachable: yes
      vars:
        ansible_user: root
      register: root_auth_check

    - name: "[SSH] Логика: настройка подключения под root"
      set_fact:
        ansible_user: root
        ansible_become: no
      when: root_auth_check.ping is defined

    - name: "[SSH] Логика: настройка sudo для обычного пользователя"
      set_fact:
        ansible_become: yes
        ansible_become_method: sudo
        ansible_become_password: "{{ user_pass }}"
      when: root_auth_check.ping is not defined

  tasks:
    - name: "[Python] Установка Python3 (необходим для работы Ansible)"
      raw: |
        if [ "$USER" != "root" ]; then SUDO="sudo"; else SUDO=""; fi
        
        if command -v apt-get >/dev/null; then
            $SUDO apt-get update && $SUDO env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=l apt-get install -y python3
        elif command -v pacman >/dev/null; then
            $SUDO pacman -Sy --noconfirm --overwrite "*" archlinux-keyring && $SUDO pacman -Syu --noconfirm --overwrite "*" python3
        else
            echo "Unsupported distribution" >&2
            exit 1
        fi
      changed_when: false

    - name: "[Facts] Сбор системных фактов после установки Python"
      setup:

    - name: "[Общее] Проверка поддерживаемой ОС (Debian/Ubuntu или Arch)"
      fail:
        msg: "Неподдерживаемая ОС. Требуется Debian/Ubuntu или Arch Linux"
      when:
        - ansible_facts['os_family'] != 'Debian'
        - ansible_facts['os_family'] != 'Archlinux'

    - name: "[Bootstrap] Запуск сценария базовой настройки ОС"
      include_tasks: tasks/bootstrap_os.yml

  handlers:
    - name: Restart SSH
      ansible.builtin.systemd:
        name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
        state: restarted

- name: "[Git] Синхронизация репозитория ServeHub-2"
  hosts: vps, local
  vars_files:
    - vars/secrets.yml
  become: yes
  tasks:
    - name: "[Git] Клонирование или обновление репозитория ServeHub-2"
      ansible.builtin.git:
        repo: "https://github.com/canntstand/ServeHub-2"
        dest: "/home/{{ deploy_user }}/ServeHub-2"
        clone: yes
        update: yes
        force: yes
      become: true
      become_user: "{{ deploy_user }}"

    - name: "[Общее] Генерация файла .env из шаблона env.j2"
      ansible.builtin.template:
        src: env.j2
        dest: "/home/{{ deploy_user }}/ServeHub-2/.env"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0600"

- name: "Настройка удалённой инфраструктуры (VPS)"
  hosts: vps
  vars_files:
    - vars/secrets.yml
  become: yes
  tasks:
    - name: "[VPS] Запуск нативных задач настройки удалённого сервера"
      include_tasks: tasks/setup_remote.yml

- name: "[Pause] Ожидание конфигурации WireGuard"
  hosts: localhost
  connection: local
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: "[Pause] Пауза для ручной генерации конфига (wg-easy)"
      ansible.builtin.pause:
        prompt: |
          ======================================================================
          ⚙️ НАСТРОЙКА WIREGUARD И PROMETHEUS (РУЧНОЙ ШАГ):
          ======================================================================
          1. Откройте туннель: ssh -L 51821:127.0.0.1:51821 {{ vps_user }}@{{ vps_public_ip }}
          2. Зайдите в браузер: http://127.0.0.1:51821
          3. Включите Prometheus в настройках wg-easy.
          4. Создайте клиента для локального сервера с ip 10.8.0.2 и скачайте файл конфигурации (либо просто скопируйте текст).
          5. Можно также сразу создать клиентов для остальных устройств (можно будет сделать потом)
          6. Сохраните его на вашем локальном сервере по пути: ./configs/amnezia/awg0.conf (можно подключиться по ssh {{ local_user }}@{{ local_private_ip }})
          7. ВАЖНО: Если вы заново разворачиваете проект, сейчас вы можете положить старую папку apps-data в /home/user/ServeHub-2 и PersonalData в /home/user/ на локальном сервере.
          ======================================================================
          Как только файл на месте, нажмите ENTER для продолжения деплоя...

- name: "Настройка локальной инфраструктуры (Local Server)"
  hosts: local
  vars_files:
    - vars/secrets.yml
  become: yes
  tasks:
    - name: "Проверка наличия конфигурационного файла"
      ansible.builtin.stat:
        path: "/home/{{ deploy_user }}/ServeHub-2/configs/amnezia/awg0.conf"
      register: wg_config

    - name: "Ошибка: отсутствует файл конфигурации WireGuard"
      ansible.builtin.fail:
        msg: "WireGuard конфиг не найден! Пожалуйста, создайте его перед продолжением."
      when: not wg_config.stat.exists

    - name: "[Local] Запуск нативных задач настройки локального сервера"
      include_tasks: tasks/setup_local.yml
