[vps]
vps-server 

[local]
local-server 

[localhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[vagrant]
arch-node    ansible_host=192.168.56.10 deploy_user=vagrant is_vagrant=true
debian-node  ansible_host=192.168.56.11 deploy_user=vagrant is_vagrant=true
ubuntu-node  ansible_host=192.168.56.12 deploy_user=vagrant is_vagrant=true

[vagrant:vars]
ansible_user=vagrant