source_directories:
  - /home/${LOCAL_USER}/ServeHub-2/apps-data/
  - /home/${LOCAL_USER}/Music
  - /home/${LOCAL_USER}/NextcloudData
  - /home/${LOCAL_USER}/Books
  - /home/${LOCAL_USER}/Podcasts
  - /home/${LOCAL_USER}/Audiobooks
  - /var/lib/docker/volumes/

repositories:
  - path: /mnt/backup_storage/server_backup.borg

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

encryption_passphrase: "${BORGMATIC_ENCRYPTION_PASSPHRASE}"

commands:
  - before: action
    when:
      - create
    run:
      - echo "Starting backup pipeline..."
      - cd /home/${LOCAL_USER}/ServeHub-2 && docker compose -f docker-compose.local.yaml down

  - after: action
    when:
      - create
    states:
      - finish
    run:
      - cd /home/${LOCAL_USER}/ServeHub-2 && docker compose -f docker-compose.local.yaml up -d
      - echo "Backup completed successfully!"

  - after: error
    run:
      - cd /home/${LOCAL_USER}/ServeHub-2 && docker compose -f docker-compose.local.yaml up -d
      - echo "Backup failed! Containers restarted."